version: 0.2
env:
  variables:
    IMAGE_TAG: latest
phases:
  pre_build:
    commands:
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPO=streamlit-weather
      - REPO_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${REPO}
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${REPO_URI}
  build:
    commands:
      - docker build -t ${REPO_URI}:${IMAGE_TAG} .
  post_build:
    commands:
      - docker push ${REPO_URI}:${IMAGE_TAG}
      # Emit Dockerrun for EB
      - printf '{"AWSEBDockerrunVersion":"1","Image":{"Name":"%s","Update":"true"},"Ports":[{"ContainerPort":"8080"}]}\n' ${REPO_URI}:${IMAGE_TAG} > Dockerrun.aws.json
artifacts:
  files:
    - Dockerrun.aws.json
